spring:
  application:
    name: gymflow-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gymflow}
    username: ${DB_USERNAME:gymflow}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    web:
      pageable:
        max-page-size: 100

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.renatoboranga.gymflow: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  info:
    java:
      enabled: true
    os:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

info:
  app:
    name: GymFlow API
    description: API REST para gestão de academias
    java: 21
