CREATE TABLE planos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    numero_treinos INTEGER NOT NULL,
    cliente_id BIGINT NOT NULL,
    CONSTRAINT ck_planos_numero_treinos_positivo CHECK (numero_treinos > 0),
    CONSTRAINT fk_planos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

CREATE INDEX idx_planos_cliente_id ON planos (cliente_id);
