CREATE TABLE treinos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(240) NOT NULL,
    data DATE NOT NULL,
    plano_id BIGINT NOT NULL,
    professor_id BIGINT NOT NULL,
    CONSTRAINT fk_treinos_plano FOREIGN KEY (plano_id) REFERENCES planos (id),
    CONSTRAINT fk_treinos_professor FOREIGN KEY (professor_id) REFERENCES professores (id)
);

CREATE INDEX idx_treinos_plano_id ON treinos (plano_id);
CREATE INDEX idx_treinos_professor_id ON treinos (professor_id);
